### PR TITLE
Activity 8 submission

### PR DESCRIPTION
**Pull request by ericrosko**
I put my code in the unit-test.py file.

### CODE REVIEW

**Comment by mdgregor** [comment]
So you'll need to remove your change to the `.gitignore` at the root of the repo.  Reach out to me if you need help on figuring out what to do.

**Comment by ericrosko** [comment]
When I look at this pull request from my end, it says "This branch has no conflicts with the base branch".  The last commit was me re-adding the original .gitignore from the master repo.  While I originally changed the gitignore, I replaced it with an exact copy of the original.  Are you saying you are still getting a merge conflict after my commit titled 'put original gitignore back'?

**Comment by ericrosko** [comment]
I supposed I could re-fork at re-commit.  What are my other options if you can't just merge it?  Thanks.

**Comment by mdgregor** [comment]
So i made a change to the base branch and I think this is going to fix a lot of people who did have conflicts :)

**Pull request merged**
